const realisationsType = {
  name: 'realisations',
  title: 'Réalisations',
  type: 'document',
  groups: [
    { name: 'identity', title: 'Identité' },
    { name: 'story', title: 'Récit' },
    { name: 'media', title: 'Médias' },
    { name: 'proof', title: 'Preuves' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    { name: 'locale', title: 'Locale', type: 'string', options: { list: [{ title: 'FR', value: 'fr' }, { title: 'RU', value: 'ru' }] }, group: 'identity', validation: (Rule) => Rule.required() },
    { name: 'title', title: 'Titre', type: 'string', group: 'identity', validation: (Rule) => Rule.required() },
    { name: 'slug', title: 'Slug', type: 'slug', group: 'identity', options: { source: 'title', maxLength: 96 }, validation: (Rule) => Rule.required() },
    { name: 'clientName', title: 'Nom client / contexte', type: 'string', group: 'identity' },
    { name: 'sector', title: 'Secteur', type: 'string', group: 'identity', validation: (Rule) => Rule.required() },
    { name: 'services', title: 'Services mobilisés', type: 'array', of: [{ type: 'string' }], group: 'identity' },
    { name: 'duration', title: 'Durée', type: 'string', group: 'identity' },
    { name: 'location', title: 'Zone / localisation', type: 'string', group: 'identity' },
    { name: 'year', title: 'Année', type: 'number', group: 'identity' },
    { name: 'summary', title: 'Résumé', type: 'text', rows: 3, group: 'story', validation: (Rule) => Rule.required() },
    { name: 'challenge', title: 'Contexte / enjeu', type: 'text', rows: 5, group: 'story', validation: (Rule) => Rule.required() },
    { name: 'solution', title: 'Réponse ACB6', type: 'text', rows: 5, group: 'story', validation: (Rule) => Rule.required() },
    { name: 'results', title: 'Résultat', type: 'text', rows: 5, group: 'story', validation: (Rule) => Rule.required() },
    { name: 'quote', title: 'Citation client ou projet', type: 'text', rows: 3, group: 'proof' },
    { name: 'quoteAuthor', title: 'Auteur citation', type: 'string', group: 'proof' },
    { name: 'quoteRole', title: 'Fonction auteur citation', type: 'string', group: 'proof' },
    { name: 'outcomeMetrics', title: 'Metriques resultat', type: 'array', of: [{ type: 'stat' }], group: 'proof' },
    { name: 'coverImage', title: 'Image principale', type: 'imageWithAlt', group: 'media' },
    { name: 'gallery', title: 'Galerie', type: 'array', of: [{ type: 'imageWithAlt' }], group: 'media' },
    { name: 'tags', title: 'Tags', type: 'array', of: [{ type: 'string' }], group: 'identity' },
    { name: 'relatedExpertises', title: 'Expertises liées', type: 'array', of: [{ type: 'reference', to: [{ type: 'expertise' }] }], group: 'proof' },
    { name: 'featured', title: 'Mis en avant', type: 'boolean', group: 'identity', initialValue: false },
    { name: 'published', title: 'Publié', type: 'boolean', group: 'identity', initialValue: true },
    { name: 'publishedAt', title: 'Date de publication', type: 'datetime', group: 'identity' },
    { name: 'seo', title: 'SEO', type: 'seo', group: 'seo' },
  ],
  orderings: [{ title: 'Publication desc', name: 'publishedDesc', by: [{ field: 'publishedAt', direction: 'desc' }] }],
  preview: { select: { title: 'title', subtitle: 'sector', locale: 'locale', media: 'coverImage.asset' }, prepare: ({ title, subtitle, locale }) => ({ title, subtitle: [locale ? locale.toUpperCase() : null, subtitle].filter(Boolean).join(' · ') }) },
};

module.exports = { realisationsType };
