import theme from '@/30_design/THEME.json';

export const siteTheme = theme;

export const cssVariables = {
  '--color-bg': theme.colors.background,
  '--color-surface': theme.colors.surface,
  '--color-surface-alt': theme.colors.surfaceAlt,
  '--color-surface-dark': theme.colors.surfaceDark,
  '--color-text': theme.colors.text,
  '--color-text-muted': theme.colors.textMuted,
  '--color-text-on-dark': theme.colors.textOnDark,
  '--color-border': theme.colors.border,
  '--color-primary': theme.colors.primary,
  '--color-primary-hover': theme.colors.primaryHover,
  '--color-primary-soft': theme.colors.primarySoft,
  '--color-secondary': theme.colors.secondary,
  '--color-success': theme.colors.success,
  '--color-warning': theme.colors.warning,
  '--color-danger': theme.colors.danger,
  '--color-focus': theme.colors.focus,
  '--font-heading': theme.fonts.heading,
  '--font-body': theme.fonts.body,
  '--font-mono': theme.fonts.mono,
  '--text-xs': theme.typography.size.xs,
  '--text-sm': theme.typography.size.sm,
  '--text-base': theme.typography.size.base,
  '--text-lg': theme.typography.size.lg,
  '--text-xl': theme.typography.size.xl,
  '--text-2xl': theme.typography.size['2xl'],
  '--text-3xl': theme.typography.size['3xl'],
  '--text-4xl': theme.typography.size['4xl'],
  '--leading-tight': String(theme.typography.lineHeight.tight),
  '--leading-snug': String(theme.typography.lineHeight.snug),
  '--leading-normal': String(theme.typography.lineHeight.normal),
  '--leading-relaxed': String(theme.typography.lineHeight.relaxed),
  '--space-1': theme.spacing['1'],
  '--space-2': theme.spacing['2'],
  '--space-3': theme.spacing['3'],
  '--space-4': theme.spacing['4'],
  '--space-6': theme.spacing['6'],
  '--space-8': theme.spacing['8'],
  '--space-12': theme.spacing['12'],
  '--space-16': theme.spacing['16'],
  '--space-24': theme.spacing['24'],
  '--space-32': theme.spacing['32'],
  '--radius-sm': theme.radius.sm,
  '--radius-md': theme.radius.md,
  '--radius-lg': theme.radius.lg,
  '--radius-xl': theme.radius.xl,
  '--radius-pill': theme.radius.pill,
  '--shadow-sm': theme.shadow.sm,
  '--shadow-md': theme.shadow.md,
  '--shadow-lg': theme.shadow.lg,
  '--container-max': theme.layout.containerMax,
  '--reading-max': theme.layout.readingMax,
  '--header-height': theme.layout.headerHeight,
  '--section-mobile': theme.layout.sectionPaddingMobile,
  '--section-desktop': theme.layout.sectionPaddingDesktop,
  '--motion-fast': theme.motion.fast,
  '--motion-base': theme.motion.base,
  '--motion-slow': theme.motion.slow,
} as const;
